(import (test-runner))

(load "sbral-tests.ss")
 ;(load "mini-substitution-tests.ss")
 ;(load "state-tests.ss")
 (load "goal-tests.ss")
 ;(load "reducer-tests.ss")
 ;(load "solver-tests.ss")
 ;(load "matcho-tests.ss")
 ;(load "negation-tests.ss")
 ;(load "dfs-tests.ss")
 (load "constraints-tests.ss")
 ;(load "listo-tests.ss")
 ;(load "tracing-tests.ss")
 ;(load "generative-tests.ss")
 ;(load "quine-tests.ss")
 ;(load "interpreter-tests.ss")

(printf "~%Testing Complete: ")
(tmessage)


#;
((run-sbral-tests)
 (run-mini-substitution-tests)
 (run-state-tests)
 (run-goal-tests)
 (run-reducer-tests)
 (run-solver-tests)
 (run-matcho-tests)
 (run-negation-tests)
 (run-dfs-tests)
 (run-constraints-tests)
 (run-listo-tests)
 (run-tracing-tests)
 (run-generative-tests)
 (run-quine-tests)
 (run-interpreter-tests)
 (parameterize ([benchmark-testing #t])
   (include "src/benchmarks/benchmarks.ss")))
