(import (test-runner))

#;
(define (run-suite filename)
  (load (string-append (path-parent (car (command-line))) (string (directory-separator)) filename)))

(load "src/tests/sbral-tests.ss")
(load "src/tests/mini-substitution-tests.ss")
(load "src/tests/state-tests.ss")
(load "src/tests/goal-tests.ss")
(load "src/tests/reducer-tests.ss")
(load "src/tests/solver-tests.ss")
(load "src/tests/matcho-tests.ss")
(load "src/tests/negation-tests.ss")
(load "src/tests/dfs-tests.ss")
(load "src/tests/constraints-tests.ss")
(load "src/tests/listo-tests.ss")
(load "src/tests/tracing-tests.ss")
(load "src/tests/generative-tests.ss")
(load "src/tests/quine-tests.ss")
(load "src/tests/interpreter-tests.ss")

(printf "~%Testing Complete: ")
(tmessage)


#;
((run-sbral-tests)
(run-mini-substitution-tests)
(run-state-tests)
(run-goal-tests)
(run-reducer-tests)
(run-solver-tests)
(run-matcho-tests)
(run-negation-tests)
(run-dfs-tests)
(run-constraints-tests)
(run-listo-tests)
(run-tracing-tests)
(run-generative-tests)
(run-quine-tests)
(run-interpreter-tests)
(parameterize ([benchmark-testing #t])
(include "src/benchmarks/benchmarks.ss")))
